### Obtener todas las provincias 
GET http://localhost:3000/api/provincia


### Obtener una provincia 
GET http://localhost:3000/api/provincia/2

### Crear una nueva provincia
POST http://localhost:3000/api/provincia
Content-Type: application/json

{
  "id":"3",
  "descripcionProvincia": "Cordoba"
}

### Modificar una nueva provincia (recurso completo e idempotente)
PUT http://localhost:3000/api/provincia/2
Content-Type: application/json

{
  "id":"2",
  "descripcionProvincia": "Entre Rios"
}

### Modificar una nueva provincia (recurso parcial)
PATCH http://localhost:3000/api/provincia/1
Content-Type: application/json

{
  "id":"1",
  "descripcionProvincia": "Misiones"
}

###Borar una provincia
DELETE http://localhost:3000/api/provincia/1
