### Obtener todas los vehiculos 
GET http://localhost:3000/api/vehiculo/find


### Obtener un vehiculo
GET http://localhost:3000/api/vehiculo/1

### Obtener vehiculo de un tipo especicifico
GET http://localhost:3000/api/vehiculo?filter=4

### Obtener vehiculos disponibles
GET http://localhost:3000/api/vehiculo/getAvailables?fecha_desde='2023-12-07T19:56:38.000Z'&fecha_hasta='2023-12-30T19:56:38.000Z'&transmision='MT'&tipo_vehiculo='1'

### Crear un nuevo vehiculo
POST http://localhost:3000/api/vehiculo
Content-Type: application/json

{
  "marca": "Chevrolet",
  "modelo": "Onix",
  "transmision": "Manual",
  "capacidad": 4,
  "image":"/assets/images/lamborghini.png",
  "tipoVehiculo": 1,
  "sucursal": 1
}

### Modificar un vehiculo (recurso completo e idempotente)
PUT http://localhost:3000/api/vehiculo/2
Content-Type: application/json

{
  "id":"2",
  "transmision": "Semi-automatica",
  "capacidad": 4,
  "disponible": 0,
  "idTipoVehiculo": 1,
  "idSeguro": 1,
  "idSucursal": 1
}

### Modificar un vehiculo (recurso parcial)
PATCH http://localhost:3000/api/vehiculo/2
Content-Type: application/json

{
  "id":"2",
  "transmision": "Automatica",
  "capacidad": 4,
  "disponible": 0,
  "idTipoVehiculo": 1,
  "idSeguro": 1,
  "idSucursal": 1
}

###Borar un vehiculo
DELETE http://localhost:3000/api/vehiculo/2