### Obtener todos los usuarios 
GET http://localhost:3000/api/usuario


### Obtener un usuario 
GET http://localhost:3000/api/usuario/6
Authorization: // probar con un token nuevo

### Login
POST http://localhost:3000/api/usuario/login
Content-Type: application/json

{
    "email": "nino@gmail.com",
    "password": "ntell"
}

### isAdmin
POST http://localhost:3000/api/usuario/verifyAdmin
Content-Type: application/json,
Authorization: // probar con un token nuevo

### Crear un nuevo usuario
POST http://localhost:3000/api/usuario/register
Content-Type: application/json

{
    "nombre": "Nino",
    "apellido": "Tell",
    "email": "nino@gmail.com",
    "password": "ntell",
    "fechaNacimiento": "1960-02-02",
    "numeroDocumento": "40345674",
    "telefono": "341654321",
    "fechaContratacion": null
}

### Modificar un nuevo usuario (recurso completo e idempotente)
PUT http://localhost:3000/api/usuario/6
Content-Type: application/json

{
    "id": 6,
    "nombre": "Nino",
    "apellido": "Tell",
    "fechaNacimiento": "1960-02-01T00:00:00.000Z",
    "numeroDocumento": "40345674",
    "telefono": "341654321",
    "fechaContratacion": null,
    "email": "nino@gmail.com",
    "password": "",
    "tipoUsuario": 1
}

### Modificar un nuevo usuario (recurso parcial)
PATCH http://localhost:3000/api/usuario/6
Content-Type: application/json

{    
    "idTipoUsuario": 2 
}

###Borar un usuario
DELETE http://localhost:3000/api/usuario/5
